apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: aws-storage-secret
  namespace: kubeflow
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::863518836478:role/my-eks-cluster_kubeflow_external-secrets-kubeflow
  data:
    - key: my-eks-cluster/kubeflow/db_name_cache
      name: db_name_cache

    - key: my-eks-cluster/kubeflow/db_name_katib
      name: db_name_katib

    - key: my-eks-cluster/kubeflow/db_name_metadata
      name: db_name_metadata

    - key: my-eks-cluster/kubeflow/db_name_pipelines
      name: db_name_pipelines

    - key: my-eks-cluster/kubeflow/rds_host
      name: rds_host

    - key: my-eks-cluster/kubeflow/rds_port
      name: rds_port

    - key: my-eks-cluster/kubeflow/rds_username
      name: rds_username

    - key: my-eks-cluster/kubeflow/s3_access_key
      name: s3_access_key

    - key: my-eks-cluster/kubeflow/s3_bucket
      name: s3_bucket

    - key: my-eks-cluster/kubeflow/s3_region
      name: s3_region

    - key: my-eks-cluster/kubeflow/s3_secret_key
      name: s3_secret_key

    - key: my-eks-cluster/kubeflow/rds_password
      name: rds_password
