"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "cert-manager-issuers"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "cert-manager"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "path": "argocd/applications/issuers"
    "repoURL": "https://gitlab.alexanderthamm.com/kaas/at-argocd.git"
    "targetRevision": "863518836478/my-eks-cluster.my-domain.com"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
